### ISSUE TITLE
smp_dfu/ble_extFlash App Core crash with `net_core_app_update.bin`

### ISSUE THREAD

**Issue by mikemoron** [aiminhua/ncs_samples#1]
The `smp_dfu/ble_extFlash` sample crashed the App Core during BLE update on nRF5340DK.

I increased the `CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096` and the update continued using **nRF Connect** without crashing. However, after reboot, the Net Core continuously reboots like this:

```
*** Booting Zephyr OS build v2.6.99-ncs1-1  ***
E: ***** BUS FAULT *****
E:   Precise data bus error
E:   BFAR Address: 0x10710200
E: r0/a1:  0x10710200  r1/a2:  0x210004eb  r2/a3:  0x0000000c
E: r3/a4:  0x210004ec r12/ip:  0x41080000 r14/lr:  0x01003191
E:  xpsr:  0x09000000
E: Faulting instruction address (r15/pc): 0x0100447c
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: (nil) (unknown)
```

Any subsequent resets have the same result.

I modified the `v1.7.1/zephyr/samples/drivers/spi_flash` example to perform a flash erase of the secondary image in the external flash adding this line:

```
rc = flash_erase(flash_dev, 0x710000, 0xf0000);
```

After building and running this, I am able to reload (`west flash`) the `smp_dfu/ble_extFlash` application and that allows the application to boot normally.

**Comment by mikemoron** [comment]
I used the Ozone debugger and a eventually discovered that the B0n bootloader is faulting because the Network Core is trying to access the image in XIP space.

The failure sequence looks something like this:

```
/c/nordic/v1.7.1/nrf/samples/nrf5340/netboot/src/main.c : bl_validate_firmware(...)
/c/nordic/v1.7.1/nrf/subsys/bootloader/bl_validation/bl_validation.c : bl_validate_firmware(..)
/c/nordic/v1.7.1/nrf/subsys/bootloader/bl_validation/bl_validation.c : validate_firmware(...)
/c/nordic/v1.7.1/nrf/subsys/bootloader/bl_validation/bl_validation.c : validation_info_find(...)
/c/nordic/v1.7.1/nrf/subsys/bootloader/bl_validation/bl_validation.c : validation_info_check(...)
/c/nordic/v1.7.1/nrf/subsys/bootloader/bl_validation/bl_validation.c : memcmp(...) BOOM!
```

The crash happens on the first attempted access to the XIP space.

My conclusion is that Network Core either **may** not or **can** not access the XIP space.

Reading the nRF5430 Product Specification v1.2, it **seems** that, with the exception of EasyDMA and code execution,  the Network Core **can** access the XIP space.

If that is the case, then it may be that the DCNF and/or SPU registers may need to be configured by the Application Core to allow the Network Core access to the XIP space.

Otherwise, if the Network Core **cannot** access the XIP space, it seems that the PCD protocol needs to be modified significantly to transfer the image through shared RAM.

- The potential maximum size of the Network Core update image is about 256K bytes.
- The potential shared RAM size is a maximum of 512K bytes.

If we assume that the MCUBoot loader uses less than 256K bytes of RAM for its operation, then there should be enough RAM to allocate to a copy of the network core update image.

Copying the image from XIP to shared RAM, and setting up the address in PCD accordingly, it would then be possible to change only the Application Core bootloader (MCUBoot) without affecting the B0n bootloader.

**Comment by mikemoron** [comment]
This "patch"/hack to `mcuboot` "resolved" the problem. This is an extension/rework of the changes made by the `ncs_samples/smp_dfu/ble_extFlash/sdk_change/ncs_v1.7.x/bootloader/mcuboot/boot/bootutil/src/loader.c` file supplied with the sample.

Essentially, I copy the image from the XIP space into a RAM buffer and use a pointer to that RAM buffer as the update image sent to the Network Core via PCD.

```
diff --git a/boot/bootutil/src/loader.c b/boot/bootutil/src/loader.c
index 7ed318e..aa5f35c 100644
--- a/boot/bootutil/src/loader.c
+++ b/boot/bootutil/src/loader.c
@@ -881,6 +881,18 @@ boot_validated_swap_type(struct boot_loader_state *state,
      * the swap info.
      */

+       /* Gigantic buffer in shared RAM */
+       static uint32_t buffer[(257*1024)/sizeof(uint32_t)];
+
+    if (strcmp(secondary_fa->fa_dev_name, "NRF_FLASH_DRV_NAME") != 0)
+    {
+        struct image_header* p = (struct image_header *)(secondary_fa->fa_off + 0x10000000); //0x10000000 is XIP base address
+               memcpy(buffer,p,sizeof(buffer));
+
+        hdr = (struct image_header *)buffer;
+
+        printk("external secondary slot %p \r",hdr);
+    }
     if (hdr->ih_magic == IMAGE_MAGIC) {
         vtable_addr = (uint32_t)hdr + hdr->ih_hdr_size;
         vtable = (uint32_t *)(vtable_addr);
```

**Comment by aiminhua** [comment]
@mikemoron Fatanstic. You got the root cause.
Netcore cannot access XIP space. The spec needs to be updated to reflect this. 
In fact, this is an old issue. I have a workaround in https://github.com/aiminhua/ncs_samples/tree/master/nrf_dfu/ble_extFlash. Most customers like nrf_dfu. I put more focus on this module. I forgot to update the smp_dfu. Sorry for the inconvenience. But I think it's well deserved since you touched the deep of NCS update.
I think you fix is simpler. Can I merge your fix in my sample?

**Comment by aiminhua** [comment]
@mikemoron Fatanstic. You got the root cause.
Netcore cannot access XIP space. The spec needs to be updated to reflect this.
In fact, this is an old issue. I have a workaround in https://github.com/aiminhua/ncs_samples/tree/master/nrf_dfu/ble_extFlash. Most customers like nrf_dfu. I put more focus on this module. I forgot to update the smp_dfu. Sorry for the inconvenience. But I think it's well deserved since you touched the deep of NCS update.
I think your fix is simpler(MCUboot uses not too much memory). Can I merge your fix in my sample?

**Comment by mikemoron** [comment]
> You got the root cause. Netcore cannot access XIP space. The spec needs to be updated to reflect this.

Indeed. It should be a bit more obvious.

The only hint that I found in the **nRF5340 Product Specification v1.2** was in the diagram **Figure 27: Memory layout**, which is in section **5.3 Memory**, which is in the section **5 Application core** that describes the **Application Core**, when the issue is really important to the **Network Core**.

Also, the second sentence in "Note" in section **3.2 Memory** hints at this fact.

> Note: The EasyDMA masters of the network core peripherals cannot access the application core
RAM. The network core processor cannot execute code directly from the application core flash or
access QSPI XIP memories.

Again, there is nothing in the the **Network core** section regarding this limitation.

> In fact, this is an old issue. I have a workaround in https://github.com/aiminhua/ncs_samples/tree/master/nrf_dfu/ble_extFlash. Most customers like nrf_dfu. I put more focus on this module. I forgot to update the smp_dfu. Sorry for the inconvenience. 

I looked at `nrf_dfu`, but I cannot identify this work-around. Will you kindly point me at the specifics? 

> But I think it's well deserved since you touched the deep of NCS update. I think your fix is simpler(MCUboot uses not too much memory). Can I merge your fix in my sample?

Of course. However, it seems to me that this little hack needs to be done with more finesse upstream in the `mcuboot` project.

Finally, are these samples going to be integrated into the NCS SDK at some point, getting rid of the `sdk_changes` directories in the samples and upstreaming the changes?

As it is, integrating this work into our product is going to be ... challenging.

**Comment by aiminhua** [comment]
You can refer to: https://github.com/aiminhua/ncs_samples/blob/master/nrf_dfu/ble_extFlash/sdk_change/ncs_v1.7.x/nrf/subsys/pcd/src/pcd.c for the workaround. I changed pcd.c to achieve the same goal. As I mentioned before, your fix is simpler and better.
Could you send me a mail(you can find it in git log)? Let's address other topics in the mail.
